name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Format check
        run: |
          gofmt -l .
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Run 'go fmt ./...'"
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build binary
        run: go build -o app -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.ref_name }}
          path: app
