name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Format check
        run: |
          gofmt -l .
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Run 'go fmt ./...'"
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build for multiple platforms
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o app-linux-amd64

          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o app-linux-arm64

          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o app-darwin-amd64

          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o app-darwin-arm64

          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -o app-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-linux-amd64
            app-linux-arm64
            app-darwin-amd64
            app-darwin-arm64
            app-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
